### ISSUE TITLE
Exceptions on comment crud form

### ISSUE THREAD

**Issue by thedevonthompson** [nubzoar/CPW212TicketingSystem#17]
When no comment in the list box is selected, and the edit button is clicked, and unhandled exception is thrown.

**Comment by thedevonthompson** [comment]
This exception also occurs when the delete button is clicked and no comment is selected.

**Comment by thedevonthompson** [comment]
An unhandled exception is thrown when adding a comment with no text, or when editing a comment to have no text.

**Comment by Alex-Ram** [comment]
All tasks have been completed by offering more validation on the client side.
